pipelines:
    default:
        - step:
            image: luminositylabs/maven:3.6.3_openjdk-11.0.9.1_zulu-alpine-11.43.55
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging clean install
                - mvn -f src/test -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging clean install
