pipelines:
    default:
        - step:
            image: luminositylabs/maven:3.6.0_openjdk-8u192_zulu-alpine-8.33.0.1
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging clean install
                - mvn -f src/test -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging clean install
